apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-02-11T15:28:07Z"
  labels:
    io.kompose.service: server
  name: server-service
  namespace: default
  resourceVersion: "3495"
  uid: edc31e58-75ab-4f68-b54a-5a6bfc13b9c9
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.100.226.243
  clusterIPs:
  - 10.100.226.243
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30204
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    io.kompose.service: server
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 127.0.0.1