apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-02-12T12:27:33Z"
  labels:
    io.kompose.service: envoy
  name: envoy-lb
  namespace: default
  resourceVersion: "56580"
  uid: 0a036852-238e-4fc1-9893-bfeafbaa07a2
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.110.115.253
  clusterIPs:
  - 10.110.115.253
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30580
    name: proxy
    port: 10001
    protocol: TCP
    targetPort: 8080
  - nodePort: 30581
    name: admin-dashboard
    port: 10000
    protocol: TCP
    targetPort: 9901
  selector:
    io.kompose.service: envoy
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 127.0.0.1